language: perl
os:
  - linux
dist: trusty
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.26-shrplib"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
env:
  global:
    - AUTOMATED_TESTING=1
install:
  - cpanm --quiet --installdeps --with-all-features --notest . || true
  - cpanm --quiet Getopt::Long                      || true
  - cpanm --quiet Term::ANSIColor                   || true
  - cpanm --quiet Test::More                        || true
  - cpanm --quiet Algorithm::Diff                   || true
  - cpanm --quiet Capture::Tiny                     || true
  - perl ./2lib
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
