#!/pro/bin/perl

use 5.12.1;
use warnings;

open my $fh, "<", "ccdiff";
my $src = do { local $/; <$fh> };
close $fh;

my ($vsn) = ($src =~ m/^(our .VERSION\s*=.*)/m);
$vsn =~ s/ - [0-9]{8}//;

mkdir "lib";
mkdir "lib/App";
open $fh, ">", "lib/App/ccdiff.pm";
say $fh "package App::ccdiff;\n\n$vsn\n\nuse strict;\nuse warnings\n\n1;\n\n",
    $src =~ s{.*(?=__END__\n)}{}sr;
close $fh;
